/**
 * ადმინის პანელის საკუთარი ღილაკები და წარწერები, ქართულად.
 * =========================================================
 *
 * **რატომ არის ეს `en`-ის ქვეშ და არა `ka`-ს.**
 *
 * Payload 43 ენას აწვდის — ქართული მათ შორის არ არის. და უბრალოდ დამატებაც
 * არ ხერხდება: `AcceptedLanguages` დახურული union-ია
 * (`@payloadcms/translations/dist/types.d.ts`), ანუ `ka: { … }` ტიპის შეცდომაა.
 *
 * სამაგიეროდ `i18n.translations` არსებული ენის ლექსიკონის ნაწილობრივ
 * გადაფარვას იღებს. ამიტომ პანელი „ინგლისურ“ ენაზე რჩება და სწორედ ის
 * ინგლისური ლაპარაკობს ქართულად. შედეგი იგივეა, ხერხი კი ერთადერთი.
 *
 * **რა მოჰყვება ამას.** მომხმარებელს, რომელსაც ინგლისური სჭირდება, ანგარიშის
 * პარამეტრებში ენა რუსულზე ან სხვაზე გადააქვს — ის ლექსიკონები ხელუხლებელია.
 *
 * **რა არ არის აქ.** კოლექციების, ველების და ჯგუფების დასახელებები —
 * ისინი `src/admin/labels.ts`-შია. აქ მხოლოდ თავად პანელის ღილაკებია.
 *
 * `{{label}}`, `{{count}}` და `<1>…</1>` ჩანაცვლების ადგილებია — თარგმნისას
 * ისინი უცვლელად უნდა დარჩეს, თორემ წინადადებაში ცარიელი ადგილი გაჩნდება.
 */

export const payloadKa = {
  authentication: {
    account: "ანგარიში",
    backToLogin: "შესვლის გვერდზე",
    changePassword: "პაროლის შეცვლა",
    confirmPassword: "გაიმეორე პაროლი",
    emailNotValid: "ელ. ფოსტის მისამართი არასწორია",
    forgotPassword: "პაროლი დაგავიწყდა?",
    forgotPasswordQuestion: "პაროლი დაგავიწყდა?",
    logBackIn: "ხელახლა შესვლა",
    loggedIn: "სისტემაში ხარ",
    logIn: "შესვლა",
    login: "შესვლა",
    logOut: "გასვლა",
    logout: "გასვლა",
    logoutUser: "გასვლა",
    newPassword: "ახალი პაროლი",
    resetPassword: "პაროლის აღდგენა",
    stayLoggedIn: "სისტემაში დარჩენა",
    successfullyRegisteredFirstUser: "პირველი მომხმარებელი შეიქმნა.",
    unableToVerify: "დადასტურება ვერ მოხერხდა",
    verified: "დადასტურებულია",
  },

  error: {
    accountAlreadyActivated: "ეს ანგარიში უკვე გააქტიურებულია.",
    autosaving: "ავტომატური შენახვა ვერ მოხერხდა.",
    documentNotFound:
      "ჩანაწერი ნომრით {{id}} ვერ მოიძებნა. შესაძლოა წაშლილია, არასდროს არსებულა, ან მასზე წვდომა არ გაქვს.",
    emailOrPasswordIncorrect: "ელ. ფოსტა ან პაროლი არასწორია.",
    followingFieldsInvalid_one: "შესავსებია:",
    followingFieldsInvalid_other: "შესავსებია:",
    invalidFileType: "ფაილის ტიპი არ იკითხება",
    invalidFileTypeValue: "ფაილის ტიპი არ იკითხება: {{value}}",
    correctInvalidFields: "შეასწორე მონიშნული ველები.",
    deletingTitle: "„{{title}}“ ვერ წაიშალა. სცადე ხელახლა.",
    loadingDocument: "ჩანაწერი ({{id}}) ვერ ჩაიტვირთა.",
    noMatchedField: "„{{label}}“-ს შესაბამისი ველი ვერ მოიძებნა",
    notAllowedToAccessPage: "ამ გვერდზე წვდომა არ გაქვს.",
    previewing: "წინასწარი ნახვა ვერ მოხერხდა.",
    problemUploadingFile: "ფაილის ატვირთვისას პრობლემა შეიქმნა.",
    unableToDeleteCount: "{{count}} {{label}}-იდან ვერცერთი წაიშალა.",
    unableToUpdateCount: "{{count}} {{label}}-იდან ვერცერთი განახლდა.",
    unauthorized: "წვდომა არ გაქვს — ჯერ შედი სისტემაში.",
    unknown: "უცნობი შეცდომა.",
    unspecific: "შეცდომა მოხდა.",
  },

  fields: {
    addLabel: "დაამატე {{label}}",
    addLink: "ბმულის დამატება",
    addNew: "დამატება",
    addNewLabel: "დაამატე {{label}}",
    addRelationship: "კავშირის დამატება",
    addUpload: "ფაილის დამატება",
    chooseFromExisting: "აირჩიე არსებულიდან",
    chooseLabel: "აირჩიე {{label}}",
    collapseAll: "ყველას აკეცვა",
    editLink: "ბმულის შეცვლა",
    editRelationship: "კავშირის შეცვლა",
    openInNewTab: "ახალ ჩანართში გახსნა",
    passwordsDoNotMatch: "პაროლები არ ემთხვევა",
    removeRelationship: "კავშირის მოხსნა",
    removeUpload: "ფაილის მოხსნა",
    saveChanges: "ცვლილებების შენახვა",
    searchForBlock: "ბლოკის ძებნა",
    selectExistingLabel: "აირჩიე არსებული {{label}}",
    showAll: "ყველას ჩვენება",
    swapUpload: "ფაილის შეცვლა",
    textToDisplay: "ხილული ტექსტი",
    uploadNewLabel: "ატვირთე ახალი {{label}}",
  },

  general: {
    aboutToDelete: "შენ შლი {{label}}-ს: <1>{{title}}</1>. დარწმუნებული ხარ?",
    aboutToDeleteCount_many: "შენ შლი {{count}} {{label}}-ს",
    aboutToDeleteCount_one: "შენ შლი {{count}} {{label}}-ს",
    aboutToDeleteCount_other: "შენ შლი {{count}} {{label}}-ს",
    addFilter: "ფილტრის დამატება",
    adminTheme: "პანელის თემა",
    all: "ყველა",
    allLocales: "ყველა ენა",
    and: "და",
    applyChanges: "ცვლილებების გამოყენება",
    ascending: "ზრდადობით",
    backToDashboard: "მთავარ ეკრანზე",
    cancel: "გაუქმება",
    changesNotSaved: "ცვლილებები არ შენახულა. თუ ახლა გახვალ, დაიკარგება.",
    clear: "გასუფთავება",
    clearAll: "ყველას გასუფთავება",
    close: "დახურვა",
    collapse: "აკეცვა",
    /**
     * `collections` and `globals` are Payload's two built-in nav headings —
     * everything without an `admin.group` falls into them.
     *
     * **They must not read like one of our own group names.** `groupNavItems`
     * matches a group by its *translated label*, so when this said
     * „პარამეტრები“ every entity in our settings group was swallowed by the
     * built-in Globals bucket — which sits at index 1 of the initial array and
     * therefore rendered first, above „ყოველდღიური“. The nav order looked
     * random and the cause was one word repeated in two files.
     *
     * With every entity grouped, neither heading should ever appear. If one
     * does, something lost its `admin.group` — which is exactly what these
     * two labels are now phrased to reveal.
     */
    collections: "დაუჯგუფებელი სიები",
    columns: "სვეტები",
    columnToSort: "დასალაგებელი სვეტი",
    confirm: "დადასტურება",
    confirmDeletion: "წაშლის დადასტურება",
    confirmDuplication: "დუბლირების დადასტურება",
    copied: "დაკოპირდა",
    copy: "კოპირება",
    create: "შექმნა",
    created: "შეიქმნა",
    createdAt: "შექმნის თარიღი",
    createNew: "დამატება",
    createNewLabel: "დაამატე {{label}}",
    creating: "იქმნება",
    creatingNewLabel: "იქმნება {{label}}",
    custom: "ხელით",
    dark: "მუქი",
    dashboard: "მთავარი",
    delete: "წაშლა",
    deleted: "წაშლილია",
    deletedCountSuccessfully: "{{count}} {{label}} წაიშალა.",
    deletedSuccessfully: "წაიშალა.",
    deleteLabel: "წაშალე {{label}}",
    deleting: "იშლება…",
    descending: "კლებადობით",
    document: "ჩანაწერი",
    documents: "ჩანაწერები",
    duplicate: "დუბლირება",
    edit: "შეცვლა",
    editing: "იცვლება",
    editLabel: "შეცვალე {{label}}",
    email: "ელ. ფოსტა",
    emailAddress: "ელ. ფოსტის მისამართი",
    enterAValue: "ჩაწერე მნიშვნელობა",
    error: "შეცდომა",
    errors: "შეცდომები",
    false: "არა",
    filter: "ფილტრი",
    filters: "ფილტრები",
    filterWhere: "გაფილტრე {{label}} სადაც",
    globals: "დაუჯგუფებელი გვერდები",
    goBack: "უკან",
    language: "ენა",
    lastModified: "ბოლო ცვლილება",
    leaveAnyway: "მაინც გასვლა",
    leaveWithoutSaving: "შენახვის გარეშე გასვლა",
    light: "ღია",
    livePreview: "ცოცხალი ნახვა",
    loading: "იტვირთება",
    locale: "ენა",
    locales: "ენები",
    menu: "მენიუ",
    moreOptions: "მეტი",
    moveDown: "ქვემოთ",
    moveUp: "ზემოთ",
    newPassword: "ახალი პაროლი",
    next: "შემდეგი",
    no: "არა",
    noFiltersSet: "ფილტრი არ არის",
    noLabel: "<{{label}} არ არის>",
    none: "არცერთი",
    noOptions: "ვარიანტები არ არის",
    noResults: "{{label}} ჯერ არ არის — ან ფილტრი მალავს.",
    noResultsDescription: "ან ჯერ არაფერია დამატებული, ან ზემოთ დაყენებული ფილტრი მალავს.",
    noResultsFound: "ვერაფერი მოიძებნა",
    notFound: "ვერ მოიძებნა",
    nothingFound: "ვერაფერი მოიძებნა",
    noValue: "მნიშვნელობის გარეშე",
    of: "-დან",
    open: "გახსნა",
    or: "ან",
    order: "რიგითობა",
    pageNotFound: "გვერდი ვერ მოიძებნა",
    password: "პაროლი",
    payloadSettings: "პანელის პარამეტრები",
    perPage: "თითო გვერდზე:",
    previous: "წინა",
    remove: "მოხსნა",
    reset: "საწყისზე დაბრუნება",
    row: "სტრიქონი",
    rows: "სტრიქონები",
    save: "შენახვა",
    saveChanges: "ცვლილებების შენახვა",
    saving: "ინახება…",
    searchBy: "ძებნა: {{label}}",
    select: "აირჩიე",
    selectAll: "ყველას მონიშვნა",
    selectValue: "აირჩიე მნიშვნელობა",
    sort: "დალაგება",
    stayOnThisPage: "გვერდზე დარჩენა",
    submit: "გაგზავნა",
    submitting: "იგზავნება…",
    success: "მზადაა",
    successfullyCreated: "{{label}} დაემატა.",
    successfullyDuplicated: "{{label}} დუბლირდა.",
    true: "კი",
    unauthorized: "წვდომა არ გაქვს",
    unsavedChanges: "შეუნახავი ცვლილებები გაქვს. გინდა გააგრძელო?",
    untitled: "უსათაურო",
    updatedAt: "ბოლო ცვლილება",
    updatedCountSuccessfully: "{{count}} {{label}} განახლდა.",
    updatedLabelSuccessfully: "{{label}} განახლდა.",
    updatedSuccessfully: "განახლდა.",
    updating: "ნახლდება",
    uploading: "იტვირთება",
    user: "მომხმარებელი",
    users: "მომხმარებლები",
    value: "მნიშვნელობა",
    viewing: "ნახვა",
    welcome: "მოგესალმებით",
    yes: "კი",
  },

  localization: {
    copyFrom: "საიდან",
    copyTo: "სად",
    copyToLocale: "სხვა ენაში კოპირება",
    selectLocaleToCopy: "აირჩიე ენა, საიდანაც კოპირდება",
  },

  operators: {
    contains: "შეიცავს",
    equals: "უდრის",
    exists: "არსებობს",
    isGreaterThan: "მეტია",
    isGreaterThanOrEqualTo: "მეტი ან ტოლია",
    isIn: "არის სიაში",
    isLessThan: "ნაკლებია",
    isLessThanOrEqualTo: "ნაკლები ან ტოლია",
    isLike: "ჰგავს",
    isNotEqualTo: "არ უდრის",
    isNotIn: "არ არის სიაში",
    isNotLike: "არ ჰგავს",
  },

  upload: {
    addFile: "ფაილის დამატება",
    addFiles: "ფაილების დამატება",
    bulkUpload: "რამდენიმეს ატვირთვა",
    crop: "მოჭრა",
    dragAndDrop: "ჩააგდე ფაილი",
    dragAndDropHere: "ან ჩააგდე ფაილი აქ",
    editImage: "სურათის რედაქტირება",
    fileName: "ფაილის სახელი",
    fileSize: "ზომა",
    filesToUpload: "ასატვირთი ფაილები",
    fileToUpload: "ასატვირთი ფაილი",
    focalPoint: "ფოკუსის წერტილი",
    focalPointDescription:
      "გადაათრიე წერტილი იმ ადგილას, რომელიც ყოველთვის უნდა ჩანდეს — სურათი სხვადასხვა ადგილას სხვადასხვანაირად იჭრება.",
    height: "სიმაღლე",
    lessInfo: "ნაკლები",
    moreInfo: "მეტი",
    noFile: "ფაილი არ არის",
    previewSizes: "ზომების ნახვა",
    selectFile: "აირჩიე ფაილი",
    setCropArea: "მოჭრის არე",
    setFocalPoint: "ფოკუსის დაყენება",
    sizes: "ზომები",
    width: "სიგანე",
  },

  validation: {
    emailAddress: "ჩაწერე სწორი ელ. ფოსტის მისამართი.",
    enterNumber: "ჩაწერე რიცხვი.",
    greaterThanMax: "{{value}} მეტია დასაშვებ მაქსიმუმზე ({{max}}).",
    invalidInput: "ველი არასწორადაა შევსებული.",
    invalidSelection: "არჩევანი არასწორია.",
    lessThanMin: "{{value}} ნაკლებია დასაშვებ მინიმუმზე ({{min}}).",
    longerThanMin: "მინიმუმ {{minLength}} სიმბოლო.",
    notValidDate: "„{{value}}“ თარიღად არ იკითხება.",
    required: "ეს ველი სავალდებულოა.",
    requiresAtLeast: "მინიმუმ {{count}} {{label}}.",
    requiresNoMoreThan: "მაქსიმუმ {{count}} {{label}}.",
    shorterThanMax: "მაქსიმუმ {{maxLength}} სიმბოლო.",
    trueOrFalse: "მხოლოდ „კი“ ან „არა“.",
  },

  version: {
    autosave: "ავტოშენახვა",
    changed: "შეიცვალა",
    compareVersions: "ვერსიების შედარება",
    currentDraft: "მიმდინარე მონახაზი",
    currentlyPublished: "გამოქვეყნებული",
    draft: "მონახაზი",
    draftSavedSuccessfully: "მონახაზი შენახულია.",
    lastSavedAgo: "ბოლოს შენახული {{distance}} წინ",
    preview: "წინასწარი ნახვა",
    previouslyPublished: "ადრე გამოქვეყნებული",
    publish: "გამოქვეყნება",
    publishChanges: "ცვლილებების გამოქვეყნება",
    published: "გამოქვეყნებულია",
    publishing: "ქვეყნდება…",
    restoreThisVersion: "ამ ვერსიის აღდგენა",
    restoredSuccessfully: "აღდგა.",
    revertToPublished: "გამოქვეყნებულ ვერსიაზე დაბრუნება",
    saveDraft: "მონახაზის შენახვა",
    status: "სტატუსი",
    unpublish: "გამოქვეყნების მოხსნა",
    unpublished: "გამოუქვეყნებელი",
    version: "ვერსია",
    versions: "ვერსიები",
    viewingVersions: "ვერსიები — {{documentTitle}}",
  },
} as const;
