/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    'landing-pages': LandingPage;
    services: Service;
    equipment: Equipment;
    doctors: Doctor;
    faq: Faq;
    media: Media;
    users: User;
    'analytics-aggregates': AnalyticsAggregate;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'analytics-aggregates': AnalyticsAggregatesSelect<false> | AnalyticsAggregatesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ka' | 'en' | 'ru') | ('ka' | 'en' | 'ru')[];
  globals: {
    'clinic-info': ClinicInfo;
    seo: Seo;
    'analytics-settings': AnalyticsSetting;
  };
  globalsSelect: {
    'clinic-info': ClinicInfoSelect<false> | ClinicInfoSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
  };
  locale: 'ka' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * News and articles. Georgian is the source language — a post left untranslated falls back to Georgian rather than disappearing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment, Latin letters and hyphens. Shared by all three languages.
   */
  slug: string;
  category: 'clinic' | 'guide';
  publishedAt: string;
  cover: number | Media;
  /**
   * One or two sentences. Used on the card, in the meta description and in search results.
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Up to about 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Up to about 155 characters.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photographs and images used across the site. Brand assets — the logo, icons and the hero video — deliberately stay in the codebase: they change with the design, not with the content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * For finding it in the library. Not shown on the site.
   */
  internalName?: string | null;
  /**
   * Describe what is in the picture, for screen readers and image search. Not a caption — 'Nino Osadze, prosthodontist', not 'doctor photo'.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Controlled, campaign-specific landing pages. Keep old campaign documents and slugs for history; archive them instead of reusing a URL for an unrelated campaign.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  /**
   * Internal name shown in the admin, e.g. Veneers — Summer 2026.
   */
  campaignName: string;
  /**
   * Permanent campaign URL segment, e.g. veneers-summer-2026. Do not reuse an old slug for a different campaign.
   */
  slug: string;
  status: 'draft' | 'active' | 'archived';
  /**
   * Optional campaign reference date. Status remains the publishing control.
   */
  startsAt?: string | null;
  /**
   * Optional campaign reference date. It does not archive the page automatically.
   */
  endsAt?: string | null;
  archivedBehavior?: ('keep-public' | 'ended-page' | 'redirect') | null;
  /**
   * Only a CMS landing page can be selected; draft and looping targets are rejected.
   */
  redirectTarget?: (number | null) | LandingPage;
  /**
   * Off by default for paid-campaign destinations. Only active, indexable pages enter the sitemap.
   */
  indexable?: boolean | null;
  header: {
    preset: 'minimal' | 'brand' | 'ultra-minimal';
    /**
     * Used by the Brand preset only.
     */
    trustText?: string | null;
    showPhone?: boolean | null;
    ctaLabel: string;
  };
  hero: {
    layout: 'copy-only' | 'image-right' | 'image-left' | 'full-bleed' | 'centered-editorial';
    eyebrow?: string | null;
    headline: string;
    subheadline?: string | null;
    ctaLabel: string;
    /**
     * Recommended desktop hero: 1920 × 1200 px, 16:10. Upload WebP, JPEG or PNG; Payload will optimize it. Keep the original reasonably compressed, ideally under 2 MB. Keep important subjects away from extreme edges because responsive cropping may occur.
     */
    desktopImage?: (number | null) | Media;
    /**
     * Optional dedicated mobile crop. Recommended: 1080 × 1350 px, 4:5. If omitted, the desktop image is reused and cropped responsively using its focal point.
     */
    mobileImage?: (number | null) | Media;
  };
  reasons: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  problemSolution?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  doctor?: {
    enabled?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Uses the selected doctor's existing name, role, photo and credentials.
     */
    practitioner?: (number | null) | Doctor;
  };
  stepsHeading: string;
  /**
   * Make clear that sending the form is not a confirmed appointment.
   */
  stepsIntro?: string | null;
  steps: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  testimonials?: {
    enabled?: boolean | null;
    heading?: string | null;
    /**
     * Only publish reviews the clinic can substantiate.
     */
    items?:
      | {
          quote: string;
          displayName: string;
          sourceLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  clinicSection?: {
    enabled?: boolean | null;
    image?: (number | null) | Media;
    title?: string | null;
    text?: string | null;
  };
  form: {
    showService?: boolean | null;
    showPreferredTime?: boolean | null;
    showEmail?: boolean | null;
    showMessage?: boolean | null;
    /**
     * Optional campaign service, submitted even when the service selector is hidden.
     */
    defaultService?: (number | null) | Service;
    title: string;
    intro?: string | null;
    submitLabel: string;
    successTitle: string;
    successText: string;
  };
  finalCta: {
    title: string;
    text?: string | null;
    buttonLabel: string;
  };
  ended?: {
    title?: string | null;
    text?: string | null;
    ctaLabel?: string | null;
  };
  seo?: {
    /**
     * Falls back to the campaign hero headline when empty.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the hero subheadline when empty.
     */
    metaDescription?: string | null;
    /**
     * Optional sharing image. Falls back to the desktop hero, then the site image.
     */
    socialImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The clinical team. Leave 'Published profile' off while a doctor's credentials are still being confirmed — the page then shows a short honest note instead of empty headings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  /**
   * Transliterated per language.
   */
  name: string;
  role: string;
  /**
   * Used as the anchor on the about page, e.g. /ka/about#nino-osadze
   */
  slug: string;
  order: number;
  /**
   * The chief doctor gets the larger section at the top.
   */
  isLead?: boolean | null;
  /**
   * Off = the profile renders as 'in preparation'.
   */
  published?: boolean | null;
  photo: number | Media;
  /**
   * Specialisation in a few words.
   */
  focus?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown as a large number on the lead doctor's block, e.g. '20+'.
   */
  experienceYears?: string | null;
  /**
   * Two or three words each. Rendered as chips beside the portrait, not as sentences.
   */
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Newest or oldest first — whichever reads better.
   */
  education?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reverse chronological.
   */
  experience?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Publish the strongest dozen rather than everything. A wall of sixty entries is read as noise and skipped.
   */
  training?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only languages the doctor has confirmed.
   */
  languages?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The 16 services, grouped into five clinical directions. Individual services do not get their own URL — they render as anchors on their category page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Must match an entry in components/ui/ServiceIcons.tsx — the icon is picked by slug.
   */
  slug: string;
  category: 'diagnostics-planning' | 'therapy-prevention' | 'surgery-implantation' | 'orthodontics' | 'aesthetic';
  /**
   * Lower first, within the category.
   */
  order: number;
  /**
   * One sentence. Shown on cards and in the mega menu.
   */
  blurb: string;
  /**
   * Longer opening paragraph on the category page.
   */
  lead?: string | null;
  whatsIncluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Devices and systems in the clinic. Model names are NOT translated — 'Vatech EzRay Air' is what the manufacturer and the search index both use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  /**
   * Model name as the manufacturer writes it. Same in all languages.
   */
  name: string;
  slug: string;
  group: 'diagnostics' | 'hygiene' | 'aesthetics' | 'orthodontics';
  /**
   * Lower first, within the group.
   */
  order: number;
  manufacturerName: string;
  /**
   * Official site. Published as sameAs in structured data, so it must be right.
   */
  manufacturerUrl: string;
  photo?: (number | null) | Media;
  /**
   * On = the card shows a 'photo coming' badge. The images seeded initially are labelled stand-ins; untick this once a real photograph replaces one.
   */
  photoPending?: boolean | null;
  /**
   * Where this device is actually used. Drives the cross-links from the device card into the service catalogue.
   */
  services?: (number | Service)[] | null;
  /**
   * One sentence: what it does.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Two or three short facts. These are what answer engines quote.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Answers published here are emitted as FAQPage structured data, so they can be quoted verbatim in search results and by AI assistants. Write them to be quoted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Plain text, not rich text — structured data takes a string, and a self-contained first sentence is what gets quoted.
   */
  answer: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can log in. Administrators manage accounts; editors can change content and their own password, nothing else.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administrators can add and remove accounts. Editors can change content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Anonymous daily totals. These rows contain no visitor, session, cookie, fingerprint, or IP data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-aggregates".
 */
export interface AnalyticsAggregate {
  id: number;
  /**
   * UTC calendar day (YYYY-MM-DD).
   */
  bucket: string;
  event: 'page_view' | 'booking_open' | 'booking_complete';
  /**
   * Set only for page views.
   */
  route: string;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable history of CMS changes. Entries are created automatically and cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: 'create' | 'update' | 'delete';
  targetType: 'collection' | 'global';
  target: string;
  documentId?: string | null;
  /**
   * Only changed fields are included; sensitive field names are always removed.
   */
  changes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  cover?: T;
  excerpt?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  campaignName?: T;
  slug?: T;
  status?: T;
  startsAt?: T;
  endsAt?: T;
  archivedBehavior?: T;
  redirectTarget?: T;
  indexable?: T;
  header?:
    | T
    | {
        preset?: T;
        trustText?: T;
        showPhone?: T;
        ctaLabel?: T;
      };
  hero?:
    | T
    | {
        layout?: T;
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        ctaLabel?: T;
        desktopImage?: T;
        mobileImage?: T;
      };
  reasons?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  problemSolution?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  doctor?:
    | T
    | {
        enabled?: T;
        heading?: T;
        intro?: T;
        practitioner?: T;
      };
  stepsHeading?: T;
  stepsIntro?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              quote?: T;
              displayName?: T;
              sourceLabel?: T;
              id?: T;
            };
      };
  clinicSection?:
    | T
    | {
        enabled?: T;
        image?: T;
        title?: T;
        text?: T;
      };
  form?:
    | T
    | {
        showService?: T;
        showPreferredTime?: T;
        showEmail?: T;
        showMessage?: T;
        defaultService?: T;
        title?: T;
        intro?: T;
        submitLabel?: T;
        successTitle?: T;
        successText?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
      };
  ended?:
    | T
    | {
        title?: T;
        text?: T;
        ctaLabel?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  order?: T;
  blurb?: T;
  lead?: T;
  whatsIncluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  order?: T;
  manufacturerName?: T;
  manufacturerUrl?: T;
  photo?: T;
  photoPending?: T;
  services?: T;
  summary?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  slug?: T;
  order?: T;
  isLead?: T;
  published?: T;
  photo?: T;
  focus?: T;
  bio?: T;
  experienceYears?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  education?:
    | T
    | {
        text?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        text?: T;
        id?: T;
      };
  training?:
    | T
    | {
        text?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  internalName?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-aggregates_select".
 */
export interface AnalyticsAggregatesSelect<T extends boolean = true> {
  bucket?: T;
  event?: T;
  route?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  targetType?: T;
  target?: T;
  documentId?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Phone numbers, email and address. These appear across the site and in the structured data search engines read, so a typo here is visible everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info".
 */
export interface ClinicInfo {
  id: number;
  /**
   * The mobile line — the one on WhatsApp, and the one the mobile bar dials. Write it as a person reads it: +995 511 21 16 16. The dialling format is derived automatically.
   */
  phone: string;
  /**
   * Landline, shown as a secondary number. Leave empty to hide it.
   */
  phoneAlt?: string | null;
  /**
   * Untick only if WhatsApp is on a different number.
   */
  whatsappSameAsPhone?: boolean | null;
  /**
   * The WhatsApp number, if it differs from the one above.
   */
  whatsapp?: string | null;
  email: string;
  /**
   * As shown on the contact page and in the footer.
   */
  address: string;
  /**
   * Google Maps share link for the 'directions' button.
   */
  mapsUrl?: string | null;
  /**
   * Opening hours as a sentence, e.g. 'ყოველდღე 9:00-დან 21:00-მდე'. The machine-readable version used by search engines is set in code — tell the developer if the actual hours change.
   */
  hoursText?: string | null;
  consultationFirst: number;
  consultationRepeat: number;
  /**
   * Percentage of satisfied patients. On a medical site an unsourced figure is a liability — publish it only if there is a survey behind it.
   */
  satisfiedPercent?: number | null;
  /**
   * Years the clinic has been operating.
   */
  yearsOnMarket?: number | null;
  facebook?: string | null;
  instagram?: string | null;
  /**
   * Google Business Profile URL. The single strongest trust link a local clinic can publish — it ties the site to the entity Google already ranks in Maps.
   */
  google?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What appears in the browser tab and in Google's results for each page. Leave a field empty and the built-in text is used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  home?: {
    /**
     * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
     */
    title?: string | null;
    /**
     * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
     */
    description?: string | null;
  };
  about?: {
    /**
     * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
     */
    title?: string | null;
    /**
     * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
     */
    description?: string | null;
  };
  services?: {
    /**
     * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
     */
    title?: string | null;
    /**
     * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
     */
    description?: string | null;
  };
  technology?: {
    /**
     * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
     */
    title?: string | null;
    /**
     * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
     */
    description?: string | null;
  };
  news?: {
    /**
     * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
     */
    title?: string | null;
    /**
     * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
     */
    description?: string | null;
  };
  contact?: {
    /**
     * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
     */
    title?: string | null;
    /**
     * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
     */
    description?: string | null;
  };
  categories?: {
    diagnosticsPlanning?: {
      /**
       * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
       */
      title?: string | null;
      /**
       * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
       */
      description?: string | null;
    };
    therapyPrevention?: {
      /**
       * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
       */
      title?: string | null;
      /**
       * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
       */
      description?: string | null;
    };
    surgeryImplantation?: {
      /**
       * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
       */
      title?: string | null;
      /**
       * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
       */
      description?: string | null;
    };
    orthodontics?: {
      /**
       * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
       */
      title?: string | null;
      /**
       * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
       */
      description?: string | null;
    };
    aesthetic?: {
      /**
       * Aim for about 60 characters — longer and Google truncates it. Say what the page is, not what the clinic is called; the site name is appended automatically.
       */
      title?: string | null;
      /**
       * Aim for about 155 characters. This is the sentence under the link in search results — write it to be read by a patient, not to contain keywords.
       */
      description?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Public provider IDs. A provider stays disabled when its ID is empty, and the website loads it only after visitor consent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  /**
   * Optional. GA4 is not loaded when this field is empty.
   */
  ga4MeasurementId?: string | null;
  /**
   * Optional. Meta Pixel is not loaded when this field is empty.
   */
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info_select".
 */
export interface ClinicInfoSelect<T extends boolean = true> {
  phone?: T;
  phoneAlt?: T;
  whatsappSameAsPhone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  mapsUrl?: T;
  hoursText?: T;
  consultationFirst?: T;
  consultationRepeat?: T;
  satisfiedPercent?: T;
  yearsOnMarket?: T;
  facebook?: T;
  instagram?: T;
  google?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  home?:
    | T
    | {
        title?: T;
        description?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
      };
  technology?:
    | T
    | {
        title?: T;
        description?: T;
      };
  news?:
    | T
    | {
        title?: T;
        description?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
      };
  categories?:
    | T
    | {
        diagnosticsPlanning?:
          | T
          | {
              title?: T;
              description?: T;
            };
        therapyPrevention?:
          | T
          | {
              title?: T;
              description?: T;
            };
        surgeryImplantation?:
          | T
          | {
              title?: T;
              description?: T;
            };
        orthodontics?:
          | T
          | {
              title?: T;
              description?: T;
            };
        aesthetic?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  ga4MeasurementId?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}