/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'booking-requests': BookingRequest;
    posts: Post;
    services: Service;
    doctors: Doctor;
    equipment: Equipment;
    faq: Faq;
    media: Media;
    'landing-pages': LandingPage;
    'analytics-aggregates': AnalyticsAggregate;
    users: User;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'booking-requests': BookingRequestsSelect<false> | BookingRequestsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    'analytics-aggregates': AnalyticsAggregatesSelect<false> | AnalyticsAggregatesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ka' | 'en' | 'ru') | ('ka' | 'en' | 'ru')[];
  globals: {
    'clinic-info': ClinicInfo;
    seo: Seo;
    'booking-settings': BookingSetting;
    'analytics-settings': AnalyticsSetting;
  };
  globalsSelect: {
    'clinic-info': ClinicInfoSelect<false> | ClinicInfoSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
  };
  locale: 'ka' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * პაციენტების მოთხოვნები — ახალი ყველაზე ზემოთ. ყოველი დარეკვის შემდეგ შეცვალე სტატუსი, რომ სხვამ იგივე ადამიანს აღარ დაურეკოს. მონაცემები არ იცვლება — მხოლოდ სტატუსი.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-requests".
 */
export interface BookingRequest {
  id: number;
  /**
   * ერთადერთი ველი, რომელიც აქ იცვლება.
   */
  status: 'new' | 'contacted' | 'confirmed' | 'closed' | 'spam';
  name: string;
  phone: string;
  email?: string | null;
  service?: string | null;
  preferredTime?: string | null;
  message?: string | null;
  landingSlug?: string | null;
  campaignName?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  emailNotificationStatus: 'pending' | 'sent' | 'failed' | 'skipped';
  /**
   * მხოლოდ პროვაიდერის მოკლე პასუხი. პაროლები და გასაღებები არასდროს ინახება.
   */
  emailNotificationError?: string | null;
  telegramNotificationStatus: 'pending' | 'sent' | 'failed' | 'skipped';
  /**
   * მხოლოდ პროვაიდერის მოკლე პასუხი. პაროლები და გასაღებები არასდროს ინახება.
   */
  telegramNotificationError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * სიახლეები და სტატიები. ქართული წყარო ენაა — უთარგმნელი სტატია საიტიდან არ ქრება, ქართულად ჩანს.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * მისამართის ბოლო ნაწილი: /ka/news/მისამართი. ლათინური ასოები და დეფისი. სამივე ენას ერთი და იგივე აქვს.
   */
  slug: string;
  category: 'clinic' | 'guide';
  publishedAt: string;
  cover: number | Media;
  /**
   * ერთი-ორი წინადადება. ჩანს ბარათზე და Google-ის შედეგებში — ანუ ხშირად ეს იკითხება სტატიაზე ადრე.
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * დაახლოებით 60 სიმბოლომდე.
   */
  metaTitle?: string | null;
  /**
   * დაახლოებით 155 სიმბოლომდე.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * საიტის ყველა ფოტო და სურათი. ლოგო, ხატულები და მთავარი ვიდეო აქ არ არის — ისინი დიზაინის ნაწილია და კოდში ცხოვრობს.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * მხოლოდ იმისთვის, რომ ბიბლიოთეკაში იპოვო. საიტზე არ ჩანს. ცარიელი დატოვე და ფაილის სახელი ჩაიწერება.
   */
  internalName?: string | null;
  /**
   * რა ჩანს სურათზე — ეკრანის მკითხველისთვის და სურათების ძებნისთვის. ეს ხელმოწერა არაა: „ნინო ოსაძე, ორთოპედი“, არა „ექიმის ფოტო“.
   */
  alt: string;
  /**
   * არასავალდებულო. ჩანს სურათის ქვემოთ, სადაც დიზაინი ითვალისწინებს.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 16 სერვისი, ხუთ მიმართულებად დაჯგუფებული. ცალკე სერვისს თავისი გვერდი არ აქვს — ის თავისი მიმართულების გვერდზე ჩნდება.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * ხატულა სწორედ ამ მისამართით არჩევა — თუ შეცვლი, სერვისი ხატულის გარეშე დარჩება. ცვლილებამდე დამირეკე.
   */
  slug: string;
  category: 'diagnostics-planning' | 'therapy-prevention' | 'surgery-implantation' | 'orthodontics' | 'aesthetic';
  /**
   * რიგითობა მიმართულების შიგნით. რაც უფრო მცირე რიცხვია, მით ზემოთ.
   */
  order: number;
  /**
   * ჩანს ბარათზე და ზედა მენიუში. მოკლედ — რას აკეთებს.
   */
  blurb: string;
  /**
   * გრძელი აბზაცი მიმართულების გვერდის დასაწყისში.
   */
  lead?: string | null;
  whatsIncluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * კლინიკის გუნდი. სანამ ექიმის მონაცემები დაზუსტებულია, „საიტზე გამოჩნდეს“ გამორთული დატოვე — გვერდი მაშინ მოკლე შენიშვნას აჩვენებს, ცარიელი სათაურების ნაცვლად.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  /**
   * გამორთული = გვერდი წერს „პროფილი მზადდება“.
   */
  published?: boolean | null;
  /**
   * მთავარ ექიმს გვერდის თავში დიდი ბლოკი ეთმობა. ერთი უნდა იყოს მონიშნული.
   */
  isLead?: boolean | null;
  /**
   * დიდი ციფრი მთავარი ექიმის ბლოკზე. მაგ.: 20+
   */
  experienceYears?: string | null;
  /**
   * რაც უფრო მცირე რიცხვია, მით ზემოთ დგას.
   */
  order: number;
  /**
   * ავტომატურად ივსება სახელიდან. ღუზა „ჩვენს შესახებ“ გვერდზე: /ka/about#archil-apkhadze
   */
  slug: string;
  /**
   * თითოეულ ენაზე ისე, როგორც იწერება: ქართულად — არჩილ აფხაძე, რუსულად — Арчил Апхадзе.
   */
  name: string;
  /**
   * მაგ.: ორთოპედი, კლინიკის მთავარი ექიმი.
   */
  role: string;
  photo: number | Media;
  /**
   * რამდენიმე სიტყვა — რას აკეთებს. ჩანს სახელის ქვემოთ.
   */
  focus?: string | null;
  /**
   * ორ-სამ სიტყვიანი მოკლე ფრაზები — ფოტოს გვერდით პატარა ბარათებად ჩნდება, არა წინადადებებად.
   */
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ორ-სამი აბზაცი. ეს არის ის, რასაც პაციენტი ექიმის შესახებ წაიკითხავს.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * ახლიდან ძველისკენ ან პირიქით — როგორც უკეთ იკითხება.
   */
  education?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ახლიდან ძველისკენ.
   */
  experience?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ყველაზე ძლიერი ათი-თორმეტი აჯობებს სრულ ჩამონათვალს. სამოცი ჩანაწერი ხმაურად იკითხება და პაციენტი გვერდს უვლის.
   */
  training?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * მხოლოდ ის ენები, რომლებიც ექიმმა დაადასტურა.
   */
  languages?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * კლინიკის აპარატები და სისტემები. მოდელის სახელი არ ითარგმნება — „Vatech EzRay Air“ ზუსტად ისე იწერება, როგორც მწარმოებელთან და როგორც პაციენტი ეძებს.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  group: 'diagnostics' | 'hygiene' | 'aesthetics' | 'orthodontics';
  /**
   * რიგითობა ჯგუფის შიგნით. რაც უფრო მცირე რიცხვია, მით ზემოთ.
   */
  order: number;
  /**
   * ჩართული = ბარათზე წარწერა „ფოტო მზადდება“. თავდაპირველი სურათები დროებითია — გამორთე მაშინ, როცა რეალურ ფოტოს ატვირთავ.
   */
  photoPending?: boolean | null;
  /**
   * ავტომატურად ივსება დასახელებიდან. ტექნოლოგიების გვერდზე ღუზაა: /ka/technology#vatech-cbct
   */
  slug: string;
  /**
   * ისე, როგორც მწარმოებელი წერს. სამივე ენაზე ერთნაირად.
   */
  name: string;
  manufacturerName: string;
  /**
   * ოფიციალური მისამართი. ეს ბმული Google-საც მიეწოდება, ამიტომ ზუსტი უნდა იყოს.
   */
  manufacturerUrl: string;
  photo?: (number | null) | Media;
  /**
   * ბარათიდან ბმულები ამ სერვისებზე გაიყვანება.
   */
  services?: (number | Service)[] | null;
  /**
   * რას აკეთებს ეს აპარატი.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * ორ-სამი მოკლე ფაქტი. სწორედ ესენი ხვდება Google-ის პასუხებში.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * აქ დაწერილი პასუხები Google-ს სტრუქტურირებული სახით მიეწოდება — ანუ ისინი პირდაპირ, სიტყვასიტყვით შეიძლება გამოჩნდეს ძებნის შედეგებში და AI-ასისტენტების პასუხებში. დაწერე ისე, თითქოს ციტატაა.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * მარტივი ტექსტი, ფორმატირების გარეშე. პირველი წინადადება თვითკმარი უნდა იყოს — სწორედ ის ხვდება ციტატაში.
   */
  answer: string;
  /**
   * რაც უფრო მცირე რიცხვია, მით ზემოთ.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * სარეკლამო კამპანიის გვერდები. მისამართი: /ka/slug. სავალდებულოა მხოლოდ სახელი და სათაური — დანარჩენი ველები ცარიელი რომ დატოვოთ, ტექსტი ავტომატურად ჩაისმება.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  /**
   * მხოლოდ „აქტიური“ ჩანს ვიზიტორისთვის.
   */
  status: 'draft' | 'active' | 'archived';
  /**
   * ავტომატურად ივსება სახელიდან. გვერდი გაიხსნება: /ka/slug
   */
  slug: string;
  /**
   * ფასიანი რეკლამის გვერდისთვის ჩვეულებრივ გამორთულია.
   */
  indexable?: boolean | null;
  /**
   * მხოლოდ შენიშვნა თქვენთვის.
   */
  startsAt?: string | null;
  /**
   * გვერდს ავტომატურად არ ხურავს.
   */
  endsAt?: string | null;
  archivedBehavior?: ('ended-page' | 'redirect' | 'keep-public') | null;
  redirectTarget?: (number | null) | LandingPage;
  /**
   * მხოლოდ ადმინისთვის — ვიზიტორი ვერ ხედავს. მაგ.: ვინირები — ზაფხული 2026
   */
  campaignName: string;
  hero: {
    /**
     * ერთადერთი ტექსტი, რომელიც აუცილებლად უნდა შეავსოთ.
     */
    headline?: string | null;
    subheadline?: string | null;
    eyebrow?: string | null;
    /**
     * ცარიელი დატოვეთ და ავტომატური ტექსტი ჩაისმება.
     */
    ctaLabel?: string | null;
    /**
     * სურათის გარეშე ყველა ვარიანტი ერთნაირად, ტექსტად გამოჩნდება.
     */
    layout: 'image-right' | 'image-left' | 'full-bleed' | 'centered-editorial' | 'copy-only';
    /**
     * სასურველი ზომა 1920 × 1200 px. მნიშვნელოვანი ობიექტი ცენტრთან ახლოს დატოვეთ.
     */
    desktopImage?: (number | null) | Media;
    /**
     * არასავალდებულო, 1080 × 1350 px. თუ ცარიელია, კომპიუტერის სურათი გამოიყენება.
     */
    mobileImage?: (number | null) | Media;
  };
  /**
   * 2–4 მოკლე არგუმენტი. ცარიელი რომ დატოვოთ, კლინიკის სტანდარტული სამი არგუმენტი ჩაისმება.
   */
  reasons?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  problemSolution?: {
    /**
     * მუქი ბლოკი ერთი ძლიერი შეტყობინებით.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  doctor?: {
    /**
     * იღებს ექიმის ფოტოს, როლს და კვალიფიკაციას „ექიმების“ განყოფილებიდან.
     */
    enabled?: boolean | null;
    practitioner?: (number | null) | Doctor;
    heading?: string | null;
    intro?: string | null;
  };
  /**
   * ცარიელი რომ დატოვოთ, სტანდარტული სამი ნაბიჯი ჩაისმება (დარეკვა → დროის შეთანხმება → ვიზიტი).
   */
  steps?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  stepsHeading?: string | null;
  stepsIntro?: string | null;
  testimonials?: {
    /**
     * გამოაქვეყნეთ მხოლოდ ის შეფასებები, რომელთა დადასტურებაც კლინიკას შეუძლია.
     */
    enabled?: boolean | null;
    heading?: string | null;
    items?:
      | {
          quote?: string | null;
          displayName?: string | null;
          sourceLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  clinicSection?: {
    /**
     * კლინიკის ფოტო, მისამართი და სამუშაო საათები.
     */
    enabled?: boolean | null;
    image?: (number | null) | Media;
    title?: string | null;
    text?: string | null;
  };
  /**
   * მუქი ბლოკი გვერდის ბოლოს. ცარიელი ველები ავტომატურად ივსება.
   */
  finalCta?: {
    title?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * ჩანს მხოლოდ დასრულებულ კამპანიაზე. ცარიელი ველები ავტომატურად ივსება.
   */
  ended?: {
    title?: string | null;
    text?: string | null;
    ctaLabel?: string | null;
  };
  form?: {
    title?: string | null;
    intro?: string | null;
    submitLabel?: string | null;
    successTitle?: string | null;
    successText?: string | null;
    /**
     * სახელი და ტელეფონი ყოველთვის ჩანს. ყოველი დამატებული ველი ამცირებს შევსების ალბათობას.
     */
    showService?: boolean | null;
    showPreferredTime?: boolean | null;
    showEmail?: boolean | null;
    showMessage?: boolean | null;
    /**
     * იგზავნება განაცხადთან ერთად მაშინაც, როცა არჩევანის ველი გამორთულია.
     */
    defaultService?: (number | null) | Service;
  };
  header: {
    preset: 'minimal' | 'brand' | 'ultra-minimal';
    /**
     * ჩანს მხოლოდ მეორე ვარიანტში.
     */
    trustText?: string | null;
    showPhone?: boolean | null;
    ctaLabel?: string | null;
  };
  seo?: {
    /**
     * ცარიელია — გამოიყენება მთავარი სათაური.
     */
    metaTitle?: string | null;
    /**
     * ცარიელია — გამოიყენება პირველი ეკრანის აღწერა.
     */
    metaDescription?: string | null;
    /**
     * ცარიელია — გამოიყენება პირველი ეკრანის სურათი.
     */
    socialImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * ანონიმური დღიური ჯამები. აქ არ ინახება ვიზიტორის იდენტიფიკატორი, სესია, cookie, ანაბეჭდი ან IP.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-aggregates".
 */
export interface AnalyticsAggregate {
  id: number;
  /**
   * კალენდარული დღე UTC-ით (წწწწ-თთ-დდ).
   */
  bucket: string;
  event: 'page_view' | 'booking_open' | 'booking_complete';
  /**
   * ივსება მხოლოდ გვერდის ნახვისთვის.
   */
  route: string;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * ვის შეუძლია პანელში შესვლა. ადმინისტრატორი ანგარიშებს მართავს; რედაქტორს შიგთავსის შეცვლა და საკუთარი პაროლის შეცვლა შეუძლია — მეტი არაფერი.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * ადმინისტრატორს ანგარიშების დამატება-წაშლა შეუძლია. რედაქტორს — მხოლოდ შიგთავსი.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * ვინ, რა და როდის შეცვალა. ჩანაწერები ავტომატურად იქმნება და მათი შეცვლა ან წაშლა არავის შეუძლია — არც ადმინისტრატორს.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: 'create' | 'update' | 'delete';
  targetType: 'collection' | 'global';
  target: string;
  documentLabel?: string | null;
  documentId?: string | null;
  /**
   * მხოლოდ შეცვლილი ველები — ძველი და ახალი მნიშვნელობით. გრძელი ტექსტი მოკლდება, სტატიის შიგთავსი მხოლოდ აღინიშნება. მგრძნობიარე ველების სახელები ყოველთვის ამოღებულია.
   */
  changes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-requests_select".
 */
export interface BookingRequestsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  preferredTime?: T;
  message?: T;
  landingSlug?: T;
  campaignName?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  utmTerm?: T;
  emailNotificationStatus?: T;
  emailNotificationError?: T;
  telegramNotificationStatus?: T;
  telegramNotificationError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  cover?: T;
  excerpt?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  order?: T;
  blurb?: T;
  lead?: T;
  whatsIncluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  published?: T;
  isLead?: T;
  experienceYears?: T;
  order?: T;
  slug?: T;
  name?: T;
  role?: T;
  photo?: T;
  focus?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bio?: T;
  education?:
    | T
    | {
        text?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        text?: T;
        id?: T;
      };
  training?:
    | T
    | {
        text?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  group?: T;
  order?: T;
  photoPending?: T;
  slug?: T;
  name?: T;
  manufacturerName?: T;
  manufacturerUrl?: T;
  photo?: T;
  services?: T;
  summary?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  internalName?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  status?: T;
  slug?: T;
  indexable?: T;
  startsAt?: T;
  endsAt?: T;
  archivedBehavior?: T;
  redirectTarget?: T;
  campaignName?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        eyebrow?: T;
        ctaLabel?: T;
        layout?: T;
        desktopImage?: T;
        mobileImage?: T;
      };
  reasons?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  problemSolution?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  doctor?:
    | T
    | {
        enabled?: T;
        practitioner?: T;
        heading?: T;
        intro?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  stepsHeading?: T;
  stepsIntro?: T;
  testimonials?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              quote?: T;
              displayName?: T;
              sourceLabel?: T;
              id?: T;
            };
      };
  clinicSection?:
    | T
    | {
        enabled?: T;
        image?: T;
        title?: T;
        text?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
      };
  ended?:
    | T
    | {
        title?: T;
        text?: T;
        ctaLabel?: T;
      };
  form?:
    | T
    | {
        title?: T;
        intro?: T;
        submitLabel?: T;
        successTitle?: T;
        successText?: T;
        showService?: T;
        showPreferredTime?: T;
        showEmail?: T;
        showMessage?: T;
        defaultService?: T;
      };
  header?:
    | T
    | {
        preset?: T;
        trustText?: T;
        showPhone?: T;
        ctaLabel?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-aggregates_select".
 */
export interface AnalyticsAggregatesSelect<T extends boolean = true> {
  bucket?: T;
  event?: T;
  route?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  targetType?: T;
  target?: T;
  documentLabel?: T;
  documentId?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * ტელეფონები, ფოსტა და მისამართი. ეს მონაცემები საიტის ყველა გვერდზეა და Google-საც მიეწოდება — ანუ აქ დაშვებული შეცდომა ყველგან ჩანს.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info".
 */
export interface ClinicInfo {
  id: number;
  /**
   * ის ნომერი, რომელიც WhatsApp-ზეა და რომელსაც მობილურის ღილაკი კრეფს. ჩაწერე ისე, როგორც იკითხება: +995 511 21 16 16. დასარეკი ფორმატი ავტომატურად გამოითვლება.
   */
  phone: string;
  /**
   * ჩანს მეორე ნომრად. ცარიელი დატოვე და საერთოდ არ გამოჩნდება.
   */
  phoneAlt?: string | null;
  /**
   * მონიშვნა მოხსენი მხოლოდ მაშინ, თუ WhatsApp სხვა ნომერზეა.
   */
  whatsappSameAsPhone?: boolean | null;
  whatsapp?: string | null;
  email: string;
  /**
   * ისე, როგორც კონტაქტის გვერდსა და საიტის ბოლოში უნდა ეწეროს.
   */
  address: string;
  /**
   * „როგორ მოვიდეთ“ ღილაკი ამ ბმულს ხსნის.
   */
  mapsUrl?: string | null;
  /**
   * წინადადებად, მაგ.: „ყოველდღე 9:00-დან 21:00-მდე“. Google-ისთვის განკუთვნილი ვერსია კოდშია — თუ რეალური საათები შეიცვალა, დეველოპერს აცნობე.
   */
  hoursText?: string | null;
  consultationFirst: number;
  consultationRepeat: number;
  /**
   * სამედიცინო საიტზე დაუსაბუთებელი ციფრი რისკია — გამოაქვეყნე მხოლოდ მაშინ, თუ უკან კვლევა დგას.
   */
  satisfiedPercent?: number | null;
  yearsOnMarket?: number | null;
  facebook?: string | null;
  instagram?: string | null;
  /**
   * ყველაზე ძლიერი ნდობის ბმული, რაც ადგილობრივ კლინიკას შეიძლება ჰქონდეს — ის საიტს იმ ჩანაწერს უკავშირებს, რომელსაც Google რუკებზე უკვე აჩვენებს.
   */
  google?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * რა წერია ბრაუზერის ჩანართზე და Google-ის შედეგებში თითოეული გვერდისთვის. ცარიელი ველი ნიშნავს, რომ ჩაშენებული ტექსტი გამოიყენება — ეს ხშირად სწორია.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  home?: {
    /**
     * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
     */
    title?: string | null;
    /**
     * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
     */
    description?: string | null;
  };
  about?: {
    /**
     * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
     */
    title?: string | null;
    /**
     * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
     */
    description?: string | null;
  };
  services?: {
    /**
     * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
     */
    title?: string | null;
    /**
     * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
     */
    description?: string | null;
  };
  technology?: {
    /**
     * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
     */
    title?: string | null;
    /**
     * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
     */
    description?: string | null;
  };
  news?: {
    /**
     * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
     */
    title?: string | null;
    /**
     * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
     */
    description?: string | null;
  };
  contact?: {
    /**
     * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
     */
    title?: string | null;
    /**
     * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
     */
    description?: string | null;
  };
  categories?: {
    diagnosticsPlanning?: {
      /**
       * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
       */
      title?: string | null;
      /**
       * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
       */
      description?: string | null;
    };
    therapyPrevention?: {
      /**
       * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
       */
      title?: string | null;
      /**
       * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
       */
      description?: string | null;
    };
    surgeryImplantation?: {
      /**
       * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
       */
      title?: string | null;
      /**
       * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
       */
      description?: string | null;
    };
    orthodontics?: {
      /**
       * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
       */
      title?: string | null;
      /**
       * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
       */
      description?: string | null;
    };
    aesthetic?: {
      /**
       * დაახლოებით 60 სიმბოლო — უფრო გრძელს Google ჭრის. დაწერე რა არის ეს გვერდი, არა როგორ ჰქვია კლინიკას: სახელი ავტომატურად ემატება.
       */
      title?: string | null;
      /**
       * დაახლოებით 155 სიმბოლო. ეს ის წინადადებაა, რომელიც ბმულის ქვემოთ ჩანს — დაწერე პაციენტისთვის, არა საძიებო სიტყვებისთვის.
       */
      description?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * სად მოდის ახალი ჩაწერის შესახებ შეტყობინება. ეს მისამართი შიდაა და კლინიკის საჯარო ფოსტისგან განსხვავდება.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: number;
  /**
   * ცარიელი დატოვე და სერვერზე მითითებული BOOKING_INBOX გამოიყენება.
   */
  notificationEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * საჯარო საიდენტიფიკაციო კოდები. ცარიელი ველი = სერვისი გამორთულია. ჩართულიც კი, კოდი მხოლოდ ვიზიტორის თანხმობის შემდეგ ჩაიტვირთება.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  /**
   * არასავალდებულო. ცარიელი ველი ნიშნავს, რომ GA4 საერთოდ არ იტვირთება.
   */
  ga4MeasurementId?: string | null;
  /**
   * არასავალდებულო. ცარიელი ველი ნიშნავს, რომ Meta Pixel საერთოდ არ იტვირთება.
   */
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info_select".
 */
export interface ClinicInfoSelect<T extends boolean = true> {
  phone?: T;
  phoneAlt?: T;
  whatsappSameAsPhone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  mapsUrl?: T;
  hoursText?: T;
  consultationFirst?: T;
  consultationRepeat?: T;
  satisfiedPercent?: T;
  yearsOnMarket?: T;
  facebook?: T;
  instagram?: T;
  google?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  home?:
    | T
    | {
        title?: T;
        description?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
      };
  technology?:
    | T
    | {
        title?: T;
        description?: T;
      };
  news?:
    | T
    | {
        title?: T;
        description?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
      };
  categories?:
    | T
    | {
        diagnosticsPlanning?:
          | T
          | {
              title?: T;
              description?: T;
            };
        therapyPrevention?:
          | T
          | {
              title?: T;
              description?: T;
            };
        surgeryImplantation?:
          | T
          | {
              title?: T;
              description?: T;
            };
        orthodontics?:
          | T
          | {
              title?: T;
              description?: T;
            };
        aesthetic?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  notificationEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  ga4MeasurementId?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}